kind: Deployment
apiVersion: apps/v1
metadata:
  name: test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: container
          command:
            - /bin/bash
          #  - stress-ng --matrix 0 -t 1m  
          #  - stress-ng --cpu 4 --io 3 --vm 2 --timeout 60s
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: quay.io/container-perf-tools/stress-ng
          args:
            - '-c'
            - 'while :;do sleep infinity;done'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: ocp4-worker1.aio.example.com
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600