apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: poor-man-drs
  namespace: openshift-cnv
  annotations:
    policy.open-cluster-management.io/description: Policy to create VirtMigration Objects for OCP-V VM's on overloaded nodes.
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: drs-policy-obtain-node-values
        spec:
          object-templates-raw: >
            {{- $memory_usage_percentage := 50 }} {{- $cpu_usage_percentage :=
            50 }} {{- $nodes := (lookup "v1" "Node" "" ""
            "node-role.kubernetes.io/worker").items }}

            {{- range $node:= $nodes}}
              {{/* ## TODO: Logic to normalize measurement between Ki,Mi,Gi, assumption for now is usage and allocatable are same units ## */}}
              {{/* ## OCPBUG-https://issues.redhat.com/browse/OCPBUGS-25164 ## */}}
              
              
              {{- $node_name := $node.metadata.name }}
              {{- $allocatable_cpu := $node.status.allocatable.cpu }}
              {{- $cpu_usage := (lookup "metrics.k8s.io/v1beta1" "NodeMetrics" "" $node_name).usage.cpu }}
              {{- $cpu_test2 :=  mul ( trunc (sub (len $allocatable_cpu ) 1 | toInt ) $allocatable_cpu ) $cpu_usage_percentage }}
              {{- $cpu_test3 :=  mul ( trunc (sub (len $cpu_usage) 1 | toInt ) $cpu_usage) 100 }}
              {{- $cpu_pressure := gt $cpu_test3 $cpu_test2}}


              {{- $allocatable_memory := $node.status.allocatable.memory }}
              {{- $memory_usage := (lookup "metrics.k8s.io/v1beta1" "NodeMetrics" "" $node_name).usage.memory }}
              {{- $mem_test2 :=  mul ( trunc (sub (len $allocatable_memory ) 2 | toInt ) $allocatable_memory ) $memory_usage_percentage }}
              {{- $mem_test3 :=  mul ( trunc (sub (len $memory_usage) 2 | toInt ) $memory_usage) 100 }}
              {{- $memory_pressure := gt $mem_test3 $mem_test2 }}

                - complianceType: musthave
                  objectDefinition:
                    kind: ConfigMap
                    apiVersion: v1
                    metadata:
                      name: drs-{{ $node.metadata.name }}-info
                      namespace: openshift-cnv
                      labels:
                        drs_info_file: "true"
                    data:
                      node: '{{ $node.metadata.name }}'
                      cpu_allocatable: '{{ $allocatable_cpu }}'
                      cpu_usage: '{{ $cpu_usage }}'
                      cpu_pressure: '{{ $cpu_pressure }}'
                      memory_allocatable: '{{ $allocatable_memory }}'
                      memory_usage: '{{ $memory_usage }}'
                      memory_pressure: '{{ $memory_pressure }}'
            {{- end }}
          pruneObjectBehavior: DeleteIfCreated
          remediationAction: enforce
          severity: high
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: drs-policy-rebalance-vms
        spec:
          object-templates-raw: >
            {{- $drs_values := dict "" "" }}

            {{- $virtualmachines := (lookup "kubevirt.io/v1" "VirtualMachineInstance" "" "" "!acm-drs/exclude" ).items }} 

            {{- range $vm:= $virtualmachines }}
              {{- $vm_name := $vm.metadata.name }}
              {{- $vm_node := $vm.status.nodeName }}
              {{- $configmapname := (cat "drs" $vm_node "info" | replace " " "-" ) }}
              {{- $vm_namespace := $vm.metadata.namespace }}
              {{- $vm_memory_pressure := (lookup "v1" "ConfigMap" "openshift-cnv" $configmapname "drs_info_file").data.memory_pressure | toBool }}
              {{- $vm_cpu_pressure := (lookup "v1" "ConfigMap" "openshift-cnv" $configmapname "drs_info_file").data.cpu_pressure | toBool }}
              {{- $acm_requested_reason := "" }}
              {{- $create_acm_vmim := true }}     

              {{- if or $vm_memory_pressure $vm_cpu_pressure }}

                  {{- if $vm_memory_pressure }}
                    {{- $acm_requested_reason = "memory_pressure" }}
                  {{- else }}
                    {{- $acm_requested_reason = "cpu_pressure" }}
                  {{- end }}

                  {{ $acm_vmi_migrations := (lookup "kubevirt.io/v1" "VirtualMachineInstanceMigration" $vm_namespace "" "acm_requested_migration").items }}
                  {{- range $vmim:= $acm_vmi_migrations }}
                    {{- if eq $vmim.metadata.labels.acm_vm_name $vm_name }}
                      {{- if or (eq $vmim.status.phase "Failed") (eq $vmim.status.phase "Succeeded")}}
                        {{- break }}
                      {{- else }}s
                        {{- $create_acm_vmim = false }}
                      {{- end }}
                    {{- end }}
                  {{- end }}

                  {{- if $create_acm_vmim }}
                    - complianceType: musthave
                      objectDefinition:
                        kind: VirtualMachineInstanceMigration
                        apiVersion: kubevirt.io/v1
                        metadata:
                            name: {{ $vm_name }}-{{ now.Unix }}-migration
                            namespace: {{ $vm_namespace }}
                            labels:
                              acm_requested_migration: "true"
                              acm_source_node: '{{ $vm_node }}'
                              acm_vm_name: '{{ $vm_name }}'
                              acm_migration_reason: '{{ $acm_requested_reason }}'
                        spec:
                            vmiName: {{ $vm_name }}
                    {{- end }}
              {{- end }}
            {{- end }}
          remediationAction: enforce
          severity: high
  remediationAction: enforce
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: poor-man-drs-placement
  namespace: openshift-cnv
spec:
  clusterSets:
    - drs
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: poor-man-drs-placement-binding
  namespace: openshift-cnv
placementRef:
  name: poor-man-drs-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: poor-man-drs
    apiGroup: policy.open-cluster-management.io
    kind: Policy
